[phases.setup]
nixPkgs = ['nodejs_20', 'python311', 'python311Packages.pip', 'ffmpeg']

[phases.install]
cmds = [
  'npm ci',
  'python3 -m pip install --upgrade pip',
  'python3 -m pip install yt-dlp'
]

[phases.build]
cmds = ['which yt-dlp || echo "yt-dlp not found"']

[start]
cmd = 'node server.js'