const express = require("express");
const transcriptController = require("../controllers/transcriptController");
const { apiLimiter } = require("../middleware/rateLimiting");
const rateLimit = require("express-rate-limit");
const router = express.Router();

// Stricter rate limit for transcript (heavy operation)
const transcriptLimiter = rateLimit({
  windowMs: 60 * 1000, // 1 minute
  max: 10, // 10 requests per minute per IP
  message: {
    status: "error",
    message: "Too many transcript requests. Please wait a moment.",
  },
  standardHeaders: true,
  legacyHeaders: false,
});

// ============================================
// 📝 GET TRANSCRIPT
// POST /api/v1/transcript
// Body: { url, lang, format, autoGenerated }
// format: "text" | "timestamped" | "srt"
// ============================================
router.post("/", transcriptLimiter, transcriptController.getTranscript);

// ============================================
// 🌍 GET AVAILABLE LANGUAGES
// POST /api/v1/transcript/languages
// Body: { url }
// ============================================
router.post("/languages", apiLimiter, transcriptController.getLanguages);

// ============================================
// 📥 DOWNLOAD TRANSCRIPT AS FILE
// POST /api/v1/transcript/download
// Body: { url, lang, format }
// ============================================
router.post(
  "/download",
  transcriptLimiter,
  transcriptController.downloadTranscript,
);

// ==================== 404 HANDLER ====================
router.use((req, res) => {
  res.status(404).json({
    status: "error",
    message: "Transcript endpoint not found",
    availableEndpoints: {
      "POST /api/v1/transcript": "Get transcript as JSON",
      "POST /api/v1/transcript/languages": "Get available languages",
      "POST /api/v1/transcript/download":
        "Download transcript as .txt or .srt file",
    },
  });
});

module.exports = router;
