const { spawn } = require("child_process");
const fs = require("fs-extra");
const path = require("path");
const crypto = require("crypto");
const cookieManager = require("./cookieManager");

const isProduction =
  process.env.NODE_ENV === "production" || process.env.RAILWAY_ENVIRONMENT;

const TEMP_DIR = isProduction
  ? "/tmp/transcripts"
  : path.join(__dirname, "../../temp/transcripts");

class TranscriptService {
  constructor() {
    this.ensureDir();
  }

  async ensureDir() {
    await fs.ensureDir(TEMP_DIR);
  }

  // ============================================
  // 🔥 MAIN: Get transcript from YouTube URL
  // ============================================
  async getTranscript(url, options = {}) {
    const {
      lang = "en",
      format = "text", // "text" | "timestamped" | "srt"
      autoGenerated = true,
    } = options;

    const sessionId = crypto.randomBytes(8).toString("hex");
    const outputPath = path.join(TEMP_DIR, `${sessionId}`);

    try {
      console.log(`\n📝 [${sessionId}] Fetching transcript...`);

      // Step 1: Download subtitle file
      const vttPath = await this.downloadSubtitles(
        url,
        lang,
        autoGenerated,
        outputPath,
        sessionId,
      );

      // Step 2: Parse VTT to desired format
      const rawVtt = await fs.readFile(vttPath, "utf-8");
      const result = this.parseVTT(rawVtt, format);

      // Step 3: Get video metadata (title etc)
      const meta = await this.getBasicMeta(url, sessionId);

      // Cleanup
      await this.cleanup(outputPath, sessionId);

      console.log(`✅ [${sessionId}] Transcript ready!`);

      return {
        success: true,
        data: {
          title: meta.title,
          duration: meta.duration,
          language: lang,
          format: format,
          characterCount: result.text.length,
          wordCount: result.text.split(/\s+/).filter(Boolean).length,
          transcript: result.text,
          segments: format === "timestamped" ? result.segments : undefined,
          thumbnail: meta.thumbnail,
          videoUrl: url,
        },
      };
    } catch (error) {
      await this.cleanup(outputPath, sessionId);
      console.error(`❌ [${sessionId}] Transcript failed:`, error.message);
      throw error;
    }
  }

  // ============================================
  // Download VTT subtitle file via yt-dlp
  // ============================================
  async downloadSubtitles(url, lang, autoGenerated, outputPath, sessionId) {
    return new Promise((resolve, reject) => {
      const args = [
        url,
        "--skip-download",
        "--no-playlist",
        "--socket-timeout",
        "30",
        "--retries",
        "3",
        "--js-runtimes",
        "node",
        "-o",
        outputPath,
      ];

      // Try manual subs first, then auto-generated
      if (autoGenerated) {
        args.push(
          "--write-subs",
          "--write-auto-subs",
          "--sub-langs",
          lang,
          "--sub-format",
          "vtt",
        );
      } else {
        args.push("--write-subs", "--sub-langs", lang, "--sub-format", "vtt");
      }

      // Add YouTube cookies
      cookieManager.addCookieOptions(args, "youtube");

      console.log(
        `⬇️  [${sessionId}] Downloading subtitles (lang: ${lang})...`,
      );

      const proc = spawn("yt-dlp", args);
      let stderr = "";

      proc.stderr.on("data", (d) => {
        stderr += d.toString();
      });

      proc.on("close", async (code) => {
        try {
          // Find the downloaded .vtt file
          const files = await fs.readdir(TEMP_DIR);
          const vttFile = files.find(
            (f) =>
              f.startsWith(path.basename(outputPath)) && f.endsWith(".vtt"),
          );

          if (vttFile) {
            console.log(`✅ [${sessionId}] VTT file found: ${vttFile}`);
            resolve(path.join(TEMP_DIR, vttFile));
          } else {
            // No subtitles available
            if (
              stderr.includes("no subtitles") ||
              stderr.includes("No subtitles")
            ) {
              reject(new Error("NO_SUBTITLES"));
            } else if (lang !== "en") {
              reject(new Error(`NO_SUBTITLES_LANG:${lang}`));
            } else {
              reject(new Error("NO_SUBTITLES"));
            }
          }
        } catch (e) {
          reject(e);
        }
      });

      proc.on("error", reject);

      // Timeout after 45 seconds
      setTimeout(() => reject(new Error("SUBTITLE_TIMEOUT")), 45000);
    });
  }

  // ============================================
  // 🔥 Parse VTT → Clean text or timestamped
  // ============================================
  parseVTT(vttContent, format = "text") {
    const lines = vttContent.split("\n");
    const segments = [];
    let currentStart = null;
    let currentText = [];

    for (let i = 0; i < lines.length; i++) {
      const line = lines[i].trim();

      // Skip header lines
      if (
        line === "WEBVTT" ||
        line.startsWith("Kind:") ||
        line.startsWith("Language:") ||
        line === ""
      ) {
        if (currentText.length > 0 && currentStart !== null) {
          const text = this.cleanText(currentText.join(" "));
          if (text) {
            segments.push({ time: currentStart, text });
          }
          currentText = [];
          currentStart = null;
        }
        continue;
      }

      // Timestamp line: "00:00:00.320 --> 00:00:05.680"
      if (line.includes("-->")) {
        if (currentText.length > 0 && currentStart !== null) {
          const text = this.cleanText(currentText.join(" "));
          if (text) segments.push({ time: currentStart, text });
          currentText = [];
        }
        currentStart = this.parseTimestamp(line.split("-->")[0].trim());
        continue;
      }

      // Text line
      if (currentStart !== null && line) {
        currentText.push(line);
      }
    }

    // Push last segment
    if (currentText.length > 0 && currentStart !== null) {
      const text = this.cleanText(currentText.join(" "));
      if (text) segments.push({ time: currentStart, text });
    }

    // Deduplicate consecutive identical segments (VTT often has duplicates)
    const deduped = segments.filter((seg, i) => {
      if (i === 0) return true;
      return seg.text !== segments[i - 1].text;
    });

    if (format === "timestamped") {
      return {
        text: deduped
          .map((s) => `[${this.formatTime(s.time)}] ${s.text}`)
          .join("\n"),
        segments: deduped,
      };
    }

    if (format === "srt") {
      return {
        text: deduped
          .map((s, i) => `${i + 1}\n${this.formatTimeSRT(s.time)}\n${s.text}`)
          .join("\n\n"),
        segments: deduped,
      };
    }

    // Pure text — join smartly
    return {
      text: this.joinSmartly(deduped.map((s) => s.text)),
      segments: deduped,
    };
  }

  // Join text segments into natural paragraphs
  joinSmartly(texts) {
    return texts
      .join(" ")
      .replace(/\s+/g, " ")
      .replace(/([.!?])\s+/g, "$1 ")
      .trim();
  }

  // Clean individual text line
  cleanText(text) {
    return text
      .replace(/&nbsp;/g, " ")
      .replace(/&amp;/g, "&")
      .replace(/&lt;/g, "<")
      .replace(/&gt;/g, ">")
      .replace(/<[^>]*>/g, "") // Remove HTML tags
      .replace(/\s+/g, " ")
      .trim();
  }

  parseTimestamp(ts) {
    const parts = ts.split(":").map(parseFloat);
    if (parts.length === 3) {
      return parts[0] * 3600 + parts[1] * 60 + parts[2];
    }
    return parts[0] * 60 + parts[1];
  }

  formatTime(seconds) {
    const m = Math.floor(seconds / 60);
    const s = Math.floor(seconds % 60);
    return `${m}:${s.toString().padStart(2, "0")}`;
  }

  formatTimeSRT(seconds) {
    const h = Math.floor(seconds / 3600);
    const m = Math.floor((seconds % 3600) / 60);
    const s = Math.floor(seconds % 60);
    const ms = Math.round((seconds % 1) * 1000);
    return `${h.toString().padStart(2, "0")}:${m.toString().padStart(2, "0")}:${s.toString().padStart(2, "0")},${ms.toString().padStart(3, "0")}`;
  }

  // Get basic video metadata
  async getBasicMeta(url, sessionId) {
    try {
      const { execPromise } = require("yt-dlp-wrap");
      const YTDlpWrap = require("yt-dlp-wrap").default;
      const ytDlp = new YTDlpWrap();

      const args = [
        url,
        "--dump-json",
        "--skip-download",
        "--no-playlist",
        "--socket-timeout",
        "15",
        "--js-runtimes",
        "node",
      ];

      cookieManager.addCookieOptions(args, "youtube");

      const result = await ytDlp.execPromise(args);
      const raw = JSON.parse(result);

      return {
        title: raw.title || "YouTube Video",
        duration: raw.duration || 0,
        thumbnail: raw.thumbnail || null,
      };
    } catch (e) {
      return { title: "YouTube Video", duration: 0, thumbnail: null };
    }
  }

  // Cleanup temp files
  async cleanup(outputPath, sessionId) {
    try {
      const files = await fs.readdir(TEMP_DIR);
      const toDelete = files.filter((f) =>
        f.startsWith(path.basename(outputPath)),
      );
      for (const f of toDelete) {
        await fs.remove(path.join(TEMP_DIR, f)).catch(() => {});
      }
    } catch (e) {}
  }

  // Get available languages for a video
  async getAvailableLanguages(url) {
    return new Promise((resolve) => {
      const args = [
        url,
        "--list-subs",
        "--skip-download",
        "--no-playlist",
        "--socket-timeout",
        "20",
        "--js-runtimes",
        "node",
      ];

      cookieManager.addCookieOptions(args, "youtube");

      const proc = spawn("yt-dlp", args);
      let output = "";

      proc.stdout.on("data", (d) => (output += d.toString()));
      proc.stderr.on("data", (d) => (output += d.toString()));

      proc.on("close", () => {
        const languages = [];
        const lines = output.split("\n");

        for (const line of lines) {
          // Match language lines like "en      vtt, ttml, srv3, srv2, srv1, json3"
          const match = line.match(/^\s+([a-z]{2,5}(-[A-Za-z]{2,4})?)\s+/);
          if (match) {
            languages.push(match[1]);
          }
        }

        resolve([...new Set(languages)].slice(0, 20));
      });

      setTimeout(() => resolve(["en"]), 15000);
    });
  }
}

module.exports = new TranscriptService();
