const transcriptService = require("../services/transcriptService");
const platformDetector = require("../services/platformDetector");
const cacheService = require("../services/cacheService");

// ============================================
// 🔥 GET TRANSCRIPT - Main endpoint
// POST /api/v1/transcript
// Body: { url, lang, format, autoGenerated }
// ============================================
exports.getTranscript = async (req, res) => {
  try {
    const {
      url,
      lang = "en",
      format = "text", // "text" | "timestamped" | "srt"
      autoGenerated = true,
    } = req.body;

    // Validate URL
    if (!url?.trim()) {
      return res.status(400).json({
        status: "error",
        message: "Valid YouTube URL is required",
      });
    }

    // Only allow YouTube for now
    const detection = platformDetector.detectPlatform(url.trim());
    if (!detection.success) {
      return res.status(400).json({
        status: "error",
        message: "Invalid URL. Please provide a valid YouTube URL.",
      });
    }

    if (detection.platform !== "youtube") {
      return res.status(400).json({
        status: "error",
        message: `Transcript is currently supported for YouTube only. Detected: ${detection.platformName}`,
      });
    }

    // Validate format
    const validFormats = ["text", "timestamped", "srt"];
    if (!validFormats.includes(format)) {
      return res.status(400).json({
        status: "error",
        message: `Invalid format. Use: ${validFormats.join(", ")}`,
      });
    }

    // Check cache first
    const cacheKey = `transcript:${detection.videoId}:${lang}:${format}`;
    try {
      const cached = await cacheService.get(cacheKey);
      if (cached) {
        console.log(`🚀 Transcript cache hit: ${detection.videoId}`);
        return res.status(200).json({
          status: "success",
          cached: true,
          data: cached,
        });
      }
    } catch (e) {}

    console.log(`📝 Transcript request: ${detection.videoId} (${lang})`);

    // Get transcript
    const result = await transcriptService.getTranscript(url.trim(), {
      lang,
      format,
      autoGenerated,
    });

    if (!result.success) {
      return res.status(400).json({
        status: "error",
        message: result.error || "Failed to get transcript",
      });
    }

    // Cache for 24 hours (transcripts don't change)
    try {
      await cacheService.set(cacheKey, result.data, 24 * 60 * 60);
    } catch (e) {}

    return res.status(200).json({
      status: "success",
      cached: false,
      data: result.data,
    });
  } catch (error) {
    console.error("❌ Transcript controller error:", error);

    // User friendly errors
    if (error.message === "NO_SUBTITLES") {
      return res.status(404).json({
        status: "error",
        message:
          "No transcript available for this video. The creator may have disabled captions.",
        code: "NO_SUBTITLES",
      });
    }

    if (error.message?.startsWith("NO_SUBTITLES_LANG:")) {
      const lang = error.message.split(":")[1];
      return res.status(404).json({
        status: "error",
        message: `No transcript available in "${lang}". Try English (en) instead.`,
        code: "NO_SUBTITLES_LANG",
      });
    }

    if (error.message === "SUBTITLE_TIMEOUT") {
      return res.status(408).json({
        status: "error",
        message: "Request timed out. Please try again.",
        code: "TIMEOUT",
      });
    }

    return res.status(500).json({
      status: "error",
      message: "Failed to get transcript. Please try again.",
      details:
        process.env.NODE_ENV === "development" ? error.message : undefined,
    });
  }
};

// ============================================
// 🌍 GET AVAILABLE LANGUAGES
// POST /api/v1/transcript/languages
// Body: { url }
// ============================================
exports.getLanguages = async (req, res) => {
  try {
    const { url } = req.body;

    if (!url?.trim()) {
      return res.status(400).json({
        status: "error",
        message: "Valid YouTube URL is required",
      });
    }

    const detection = platformDetector.detectPlatform(url.trim());
    if (!detection.success || detection.platform !== "youtube") {
      return res.status(400).json({
        status: "error",
        message: "Please provide a valid YouTube URL",
      });
    }

    // Check cache
    const cacheKey = `transcript:langs:${detection.videoId}`;
    try {
      const cached = await cacheService.get(cacheKey);
      if (cached) {
        return res.status(200).json({
          status: "success",
          cached: true,
          data: cached,
        });
      }
    } catch (e) {}

    const languages = await transcriptService.getAvailableLanguages(url.trim());

    const data = {
      videoId: detection.videoId,
      languages: languages,
      total: languages.length,
    };

    // Cache for 6 hours
    try {
      await cacheService.set(cacheKey, data, 6 * 60 * 60);
    } catch (e) {}

    return res.status(200).json({
      status: "success",
      cached: false,
      data,
    });
  } catch (error) {
    console.error("❌ Languages error:", error);
    return res.status(500).json({
      status: "error",
      message: "Failed to get available languages",
    });
  }
};

// ============================================
// 📥 DOWNLOAD TRANSCRIPT AS FILE
// POST /api/v1/transcript/download
// Body: { url, lang, format }
// Returns: .txt or .srt file directly
// ============================================
exports.downloadTranscript = async (req, res) => {
  try {
    const { url, lang = "en", format = "text" } = req.body;

    if (!url?.trim()) {
      return res.status(400).json({
        status: "error",
        message: "Valid YouTube URL is required",
      });
    }

    const detection = platformDetector.detectPlatform(url.trim());
    if (!detection.success || detection.platform !== "youtube") {
      return res.status(400).json({
        status: "error",
        message: "Please provide a valid YouTube URL",
      });
    }

    const result = await transcriptService.getTranscript(url.trim(), {
      lang,
      format,
      autoGenerated: true,
    });

    if (!result.success) {
      return res.status(400).json({
        status: "error",
        message: "Failed to get transcript",
      });
    }

    // Set download headers
    const ext = format === "srt" ? "srt" : "txt";
    const safeTitle = (result.data.title || "transcript")
      .replace(/[^a-z0-9]/gi, "_")
      .toLowerCase()
      .substring(0, 50);

    const filename = `${safeTitle}_transcript.${ext}`;

    res.setHeader("Content-Type", "text/plain; charset=utf-8");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename*=UTF-8''${encodeURIComponent(filename)}`,
    );
    res.setHeader("Access-Control-Allow-Origin", "*");

    return res.send(result.data.transcript);
  } catch (error) {
    console.error("❌ Download transcript error:", error);

    if (error.message === "NO_SUBTITLES") {
      return res.status(404).json({
        status: "error",
        message: "No transcript available for this video.",
        code: "NO_SUBTITLES",
      });
    }

    return res.status(500).json({
      status: "error",
      message: "Failed to download transcript",
    });
  }
};
